-- MySQL Script generated by MySQL Workbench
-- Tue Nov  1 16:22:48 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Oficina
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Oficina` ;

-- -----------------------------------------------------
-- Schema Oficina
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Oficina` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `Oficina` ;

-- -----------------------------------------------------
-- Table `Oficina`.`Avaliação`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Oficina`.`Avaliação` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Oficina`.`Avaliação` (
  `idAvaliação` INT NOT NULL,
  `Defeito_Apresentado` VARCHAR(45) NOT NULL,
  `Conserto` TINYINT NOT NULL,
  `Revisao` TINYINT NOT NULL,
  `Veiculo_idVeiculo` INT NOT NULL,
  `Veiculo_Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idAvaliação`, `Veiculo_idVeiculo`, `Veiculo_Cliente_idCliente`),
  CONSTRAINT `fk_Avaliação_Veiculo1`
    FOREIGN KEY (`Veiculo_idVeiculo` , `Veiculo_Cliente_idCliente`)
    REFERENCES `Oficina`.`Veiculo` (`idVeiculo` , `Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Avaliação_Veiculo1_idx` ON `Oficina`.`Avaliação` (`Veiculo_idVeiculo` ASC, `Veiculo_Cliente_idCliente` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Oficina`.`Calculo_Serviço`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Oficina`.`Calculo_Serviço` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Oficina`.`Calculo_Serviço` (
  `idCalculo_Serviço` INT NOT NULL,
  `Ordem de Serviço_idOrdem de Serviço` INT NOT NULL,
  `Ordem de Serviço_Mão de Obra_idMão de Obra` INT NOT NULL,
  `Peças_idPeças` INT NOT NULL,
  `Peças_Serviços_idServiços` INT NOT NULL,
  `Peças_Serviços_Mecânico_idMecanico` INT NOT NULL,
  PRIMARY KEY (`idCalculo_Serviço`, `Ordem de Serviço_idOrdem de Serviço`, `Ordem de Serviço_Mão de Obra_idMão de Obra`, `Peças_idPeças`, `Peças_Serviços_idServiços`, `Peças_Serviços_Mecânico_idMecanico`),
  CONSTRAINT `fk_Calculo_Serviço_Ordem de Serviço1`
    FOREIGN KEY (`Ordem de Serviço_idOrdem de Serviço` , `Ordem de Serviço_Mão de Obra_idMão de Obra`)
    REFERENCES `Oficina`.`Ordem de Serviço` (`idOrdem de Serviço` , `Mão de Obra_idMão de Obra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Calculo_Serviço_Peças1`
    FOREIGN KEY (`Peças_idPeças` , `Peças_Serviços_idServiços` , `Peças_Serviços_Mecânico_idMecanico`)
    REFERENCES `Oficina`.`Peças` (`idPeças` , `Serviços_idServiços` , `Serviços_Mecânico_idMecanico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Calculo_Serviço_Ordem de Serviço1_idx` ON `Oficina`.`Calculo_Serviço` (`Ordem de Serviço_idOrdem de Serviço` ASC, `Ordem de Serviço_Mão de Obra_idMão de Obra` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Calculo_Serviço_Peças1_idx` ON `Oficina`.`Calculo_Serviço` (`Peças_idPeças` ASC, `Peças_Serviços_idServiços` ASC, `Peças_Serviços_Mecânico_idMecanico` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Oficina`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Oficina`.`Cliente` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Oficina`.`Cliente` (
  `idCliente` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Telefone` VARCHAR(45) NOT NULL,
  `Endereço` VARCHAR(45) NOT NULL,
  `CPF` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Oficina`.`Conserto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Oficina`.`Conserto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Oficina`.`Conserto` (
  `idConserto` INT NOT NULL,
  `Avaliação_idAvaliação` INT NOT NULL,
  `Avaliação_Veiculo_idVeiculo` INT NOT NULL,
  `Avaliação_Veiculo_Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idConserto`, `Avaliação_idAvaliação`, `Avaliação_Veiculo_idVeiculo`, `Avaliação_Veiculo_Cliente_idCliente`),
  CONSTRAINT `fk_Conserto_Avaliação1`
    FOREIGN KEY (`Avaliação_idAvaliação` , `Avaliação_Veiculo_idVeiculo` , `Avaliação_Veiculo_Cliente_idCliente`)
    REFERENCES `Oficina`.`Avaliação` (`idAvaliação` , `Veiculo_idVeiculo` , `Veiculo_Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Conserto_Avaliação1_idx` ON `Oficina`.`Conserto` (`Avaliação_idAvaliação` ASC, `Avaliação_Veiculo_idVeiculo` ASC, `Avaliação_Veiculo_Cliente_idCliente` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Oficina`.`Equipe_Revisão`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Oficina`.`Equipe_Revisão` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Oficina`.`Equipe_Revisão` (
  `idEquipe_Revisão` INT NOT NULL,
  `Revisão_idRevisão` INT NOT NULL,
  `Revisão_Avaliação_idAvaliação` INT NOT NULL,
  `Revisão_Avaliação_Veiculo_idVeiculo` INT NOT NULL,
  `Revisão_Avaliação_Veiculo_Cliente_idCliente` INT NOT NULL,
  `Mecânico_idMecanico` INT NOT NULL,
  PRIMARY KEY (`idEquipe_Revisão`, `Revisão_idRevisão`, `Revisão_Avaliação_idAvaliação`, `Revisão_Avaliação_Veiculo_idVeiculo`, `Revisão_Avaliação_Veiculo_Cliente_idCliente`),
  CONSTRAINT `fk_Equipe_Revisão_Revisão1`
    FOREIGN KEY (`Revisão_idRevisão` , `Revisão_Avaliação_idAvaliação` , `Revisão_Avaliação_Veiculo_idVeiculo` , `Revisão_Avaliação_Veiculo_Cliente_idCliente`)
    REFERENCES `Oficina`.`Revisão` (`idRevisão` , `Avaliação_idAvaliação` , `Avaliação_Veiculo_idVeiculo` , `Avaliação_Veiculo_Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipe_Revisão_Mecânico1`
    FOREIGN KEY (`Mecânico_idMecanico`)
    REFERENCES `Oficina`.`Mecânico` (`idMecanico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Equipe_Revisão_Revisão1_idx` ON `Oficina`.`Equipe_Revisão` (`Revisão_idRevisão` ASC, `Revisão_Avaliação_idAvaliação` ASC, `Revisão_Avaliação_Veiculo_idVeiculo` ASC, `Revisão_Avaliação_Veiculo_Cliente_idCliente` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Equipe_Revisão_Mecânico1_idx` ON `Oficina`.`Equipe_Revisão` (`Mecânico_idMecanico` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Oficina`.`Equipe_conserto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Oficina`.`Equipe_conserto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Oficina`.`Equipe_conserto` (
  `idEquipe_Conserto` INT NOT NULL,
  `Conserto_idConserto` INT NOT NULL,
  `Conserto_Avaliação_idAvaliação` INT NOT NULL,
  `Conserto_Avaliação_Veiculo_idVeiculo` INT NOT NULL,
  `Conserto_Avaliação_Veiculo_Cliente_idCliente` INT NOT NULL,
  `Mecânico_idMecanico` INT NOT NULL,
  PRIMARY KEY (`idEquipe_Conserto`, `Conserto_idConserto`, `Conserto_Avaliação_idAvaliação`, `Conserto_Avaliação_Veiculo_idVeiculo`, `Conserto_Avaliação_Veiculo_Cliente_idCliente`),
  CONSTRAINT `fk_Equipe_conserto_Conserto1`
    FOREIGN KEY (`Conserto_idConserto` , `Conserto_Avaliação_idAvaliação` , `Conserto_Avaliação_Veiculo_idVeiculo` , `Conserto_Avaliação_Veiculo_Cliente_idCliente`)
    REFERENCES `Oficina`.`Conserto` (`idConserto` , `Avaliação_idAvaliação` , `Avaliação_Veiculo_idVeiculo` , `Avaliação_Veiculo_Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipe_conserto_Mecânico1`
    FOREIGN KEY (`Mecânico_idMecanico`)
    REFERENCES `Oficina`.`Mecânico` (`idMecanico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Equipe_conserto_Conserto1_idx` ON `Oficina`.`Equipe_conserto` (`Conserto_idConserto` ASC, `Conserto_Avaliação_idAvaliação` ASC, `Conserto_Avaliação_Veiculo_idVeiculo` ASC, `Conserto_Avaliação_Veiculo_Cliente_idCliente` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Equipe_conserto_Mecânico1_idx` ON `Oficina`.`Equipe_conserto` (`Mecânico_idMecanico` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Oficina`.`Mecânico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Oficina`.`Mecânico` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Oficina`.`Mecânico` (
  `idMecanico` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Endereço` VARCHAR(45) NOT NULL,
  `Especialidade` ENUM('Concerto', 'Revisao') NOT NULL,
  PRIMARY KEY (`idMecanico`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Oficina`.`Mão de Obra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Oficina`.`Mão de Obra` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Oficina`.`Mão de Obra` (
  `idMão de Obra` INT NOT NULL,
  `Tabela_Mão_de_Obra` VARCHAR(45) NOT NULL,
  `Peças_idPeças` INT NOT NULL,
  `Peças_Serviços_idServiços` INT NOT NULL,
  `Peças_Serviços_Mecânico_idMecanico` INT NOT NULL,
  `Mecânico_idMecanico` INT NOT NULL,
  PRIMARY KEY (`idMão de Obra`, `Peças_idPeças`, `Peças_Serviços_idServiços`, `Peças_Serviços_Mecânico_idMecanico`),
  CONSTRAINT `fk_Mão de Obra_Peças1`
    FOREIGN KEY (`Peças_idPeças` , `Peças_Serviços_idServiços` , `Peças_Serviços_Mecânico_idMecanico`)
    REFERENCES `Oficina`.`Peças` (`idPeças` , `Serviços_idServiços` , `Serviços_Mecânico_idMecanico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mão de Obra_Mecânico1`
    FOREIGN KEY (`Mecânico_idMecanico`)
    REFERENCES `Oficina`.`Mecânico` (`idMecanico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Mão de Obra_Peças1_idx` ON `Oficina`.`Mão de Obra` (`Peças_idPeças` ASC, `Peças_Serviços_idServiços` ASC, `Peças_Serviços_Mecânico_idMecanico` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Mão de Obra_Mecânico1_idx` ON `Oficina`.`Mão de Obra` (`Mecânico_idMecanico` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Oficina`.`Ordem de Serviço`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Oficina`.`Ordem de Serviço` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Oficina`.`Ordem de Serviço` (
  `idOrdem de Serviço` INT NOT NULL,
  `Data de emissão` DATETIME NOT NULL,
  `Valor` FLOAT NOT NULL,
  `Status` ENUM('Concluida', 'Em andamento') NOT NULL,
  `Data conclusão` VARCHAR(45) NOT NULL,
  `Mão de Obra_idMão de Obra` INT NOT NULL,
  PRIMARY KEY (`idOrdem de Serviço`, `Mão de Obra_idMão de Obra`),
  CONSTRAINT `fk_Ordem de Serviço_Mão de Obra1`
    FOREIGN KEY (`Mão de Obra_idMão de Obra`)
    REFERENCES `Oficina`.`Mão de Obra` (`idMão de Obra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Ordem de Serviço_Mão de Obra1_idx` ON `Oficina`.`Ordem de Serviço` (`Mão de Obra_idMão de Obra` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Oficina`.`Peças`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Oficina`.`Peças` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Oficina`.`Peças` (
  `idPeças` INT NOT NULL,
  `Valor` DOUBLE NOT NULL,
  `Serviços_idServiços` INT NOT NULL,
  `Serviços_Mecânico_idMecanico` INT NOT NULL,
  PRIMARY KEY (`idPeças`, `Serviços_idServiços`, `Serviços_Mecânico_idMecanico`),
  CONSTRAINT `fk_Peças_Serviços1`
    FOREIGN KEY (`Serviços_idServiços` , `Serviços_Mecânico_idMecanico`)
    REFERENCES `Oficina`.`Serviços` (`idServiços` , `Mecânico_idMecanico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Peças_Serviços1_idx` ON `Oficina`.`Peças` (`Serviços_idServiços` ASC, `Serviços_Mecânico_idMecanico` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Oficina`.`Revisão`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Oficina`.`Revisão` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Oficina`.`Revisão` (
  `idRevisão` INT NOT NULL,
  `Avaliação_idAvaliação` INT NOT NULL,
  `Avaliação_Veiculo_idVeiculo` INT NOT NULL,
  `Avaliação_Veiculo_Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idRevisão`, `Avaliação_idAvaliação`, `Avaliação_Veiculo_idVeiculo`, `Avaliação_Veiculo_Cliente_idCliente`),
  CONSTRAINT `fk_Revisão_Avaliação1`
    FOREIGN KEY (`Avaliação_idAvaliação` , `Avaliação_Veiculo_idVeiculo` , `Avaliação_Veiculo_Cliente_idCliente`)
    REFERENCES `Oficina`.`Avaliação` (`idAvaliação` , `Veiculo_idVeiculo` , `Veiculo_Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Revisão_Avaliação1_idx` ON `Oficina`.`Revisão` (`Avaliação_idAvaliação` ASC, `Avaliação_Veiculo_idVeiculo` ASC, `Avaliação_Veiculo_Cliente_idCliente` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Oficina`.`Serviços`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Oficina`.`Serviços` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Oficina`.`Serviços` (
  `idServiços` INT NOT NULL,
  `Valor` DOUBLE NOT NULL,
  `Mecânico_idMecanico` INT NOT NULL,
  PRIMARY KEY (`idServiços`, `Mecânico_idMecanico`),
  CONSTRAINT `fk_Serviços_Mecânico1`
    FOREIGN KEY (`Mecânico_idMecanico`)
    REFERENCES `Oficina`.`Mecânico` (`idMecanico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Serviços_Mecânico1_idx` ON `Oficina`.`Serviços` (`Mecânico_idMecanico` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Oficina`.`Veiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Oficina`.`Veiculo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Oficina`.`Veiculo` (
  `idVeiculo` INT NOT NULL,
  `Modelo` VARCHAR(45) NOT NULL,
  `Ano` DATETIME NOT NULL,
  `Placa` VARCHAR(45) NOT NULL,
  `Cor` VARCHAR(45) NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idVeiculo`, `Cliente_idCliente`),
  CONSTRAINT `fk_Veiculo_Cliente`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `Oficina`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Veiculo_Cliente_idx` ON `Oficina`.`Veiculo` (`Cliente_idCliente` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
